title: "Python and Biopython"
author: "Manish Datt"
copyright: "2021"
#logo: images/logo-wide.svg
execute:
  execute_notebooks: "off" #"auto"

html:
  extra_navbar: ""

launch_buttons:
  binderhub_url: ""

sphinx:
  config:
    html_theme_options:
      use_download_button: false
      extra_navbar: ""
      extra_footer: <a href="https://online-learning.manishdatt.com">Online course catalogue</a>

url: "online-learning.manishdatt.com"
